sudo: required
services:
  - docker
# Use generic image to cut start-up time
language: generic
env:
  CST_REF: v1.9.1
  HADOLINT: "/tmp/hadolint"
install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.10.3/hadolint-$(uname -s)-$(uname -m)"
    && chmod 700 ${HADOLINT}
  - docker build
    --build-arg CST_REF=${CST_REF}
    --tag container-structure-test:${CST_REF}-alpine
    .
script:
  # markdown lint
  - docker run --rm -i -v $PWD:/lint/input:ro zemanlx/remark-lint:0.1.0 --frail .
  # Dockerfile lint
  - git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 ${HADOLINT}
  # structure test (self-test)
  - docker run -i --rm
    -v /var/run/docker.sock:/var/run/docker.sock
    -v ${PWD}:/test container-structure-test:${CST_REF}-alpine
    test
    --image container-structure-test:${CST_REF}-alpine
    --config /test/structure-tests.yaml
